# Generated by Django 2.2.10 on 2021-04-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20210330_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
